name: deturistaando

services:
    deturistaando-laravel-app:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: 'sail-deturistaando:dev'
        container_name: deturistaando-laravel-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - deturistaando-network
        depends_on:
            deturistaando-postgres-db:
                condition: service_healthy
            deturistaando-mailpit-dev:
                condition: service_started

    deturistaando-postgres-db:
        image: 'postgres:16-alpine'
        container_name: deturistaando-postgres-db
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'deturistaando-postgres-data:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - deturistaando-network
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            interval: 5s
            retries: 5
            start_period: 10s
            timeout: 5s

    deturistaando-mailpit-dev:
        image: 'axllent/mailpit:latest'
        container_name: deturistaando-mailpit-dev
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - deturistaando-network

networks:
    deturistaando-network:
        name: deturistaando-network
        driver: bridge

volumes:
    deturistaando-postgres-data:
        name: deturistaando-postgres-data
        driver: local
